package com.mmm.clout.userservice.common;

public enum Region {
    ALL, SEOUL, BUSAN, DAEGU, INCHEON, GWANGJU, DAEJEON,
    ULSAN, SEJONG, GYEONGGI, GANGWON, CHUNGBUK, CHUNGNAM,
    JEONBUK, JEONNAM, GYEONGBUK, GYEONGNAM, JEJU;
}